---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-pubsub
  labels:
    app: flow-pubsub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-pubsub
  template:
    metadata:
      labels:
        app: flow-pubsub
    spec:
      containers:
        - name: flow-pubsub
          image: flowlab/flow-pubsub:latest
          imagePullPolicy: IfNotPresent
