name: Build and Push [DockerHub]

on:
  push:
    tags:
      - '*.*.*'

env:
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: flow-pubsub

jobs:
  setup-build-publish:
    name: Setup, Build and Publish
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      # Build the Docker image
      - name: Build
        run: |
          VERSION=${{github.ref_name}}
          docker build \
            -t flowlab/"$IMAGE":latest \
            -t flowlab/"$IMAGE":"$VERSION" .

      - name: Setup DockerHub
        run: |
          docker login --username flowlab --password ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish all tags to DockerHub
        run: |
          docker push -a flowlab/"$IMAGE"